### ISSUE TITLE
Mod ID conflict with Statues: Rechisled

### ISSUE THREAD

**Issue by DWX12** [ShyNieke/StatuesMod#22]
## Client Info
* Minecraft Version:
1.12.2
* Forge Version: NA
* Mod Version: 0.8.7.3
* Java Version: NA

## Issue Description
There's a mod ID conflict with Lemon's Statues: Rechiseled Mod. It is an open issue on his Github, but he will not fix it, so I'm coming to you:
https://github.com/Lemonszz/Statues/issues/7

## Reproduce Steps
Start up a pack with both Statues and Statues: Rechiseled

## Additional Information
Thank you for the time and work you've spent making this mod, it is appreciated.

**Comment by Mrbysco** [comment]
I can not fix this either as this would break any pack containing Statues. Especially packs like Sky Factory.
