### ISSUE TITLE
Some statues look weird in-hand or on-item frame

### ISSUE THREAD

**Issue by SepSol** [ShyNieke/StatuesMod#29]
For example:
- the spider looks weird in my right hand (it's rendered at the top)
- the spider looks way too big inside the item frame
- the sheep is too much far from the center in the item frame
- the player model doesn't load its skin when in item frame
- the pupperfish looks like it's in the air when inside an item frame
- the sombrero is way too small when in an item frame
- the campfire statue is so close to the corners that it has texture overlapping

![image](https://user-images.githubusercontent.com/47871887/68021737-80b3ea00-fcb7-11e9-956b-b5d974d58938.png)

**NOTE**
These are some of the statues that I've tried. I did not tried all of them, but I thought it's worth pointing out.

**MY SPECS**
- Minecraft 1.14.4
- Forge 28.1.76
- OpriFine HD U F4
- Statues-1.14.4-0.1.1

**Comment by ShyNieke** [comment]
Is the player statue named? as this could be the issue.

as for the rendering from the spider in hand or the statues in the item frames this is all intended behaviour.

**Comment by SepSol** [comment]
The player skin was fixed with the fix you suggested, thanks!

As for other statues: why though?!! Why should there be an overlap in textures of campfire statue inside the item frame? Or the fish floating in the sky? Or the weird things for the spider statue? 🤔 

I wanted to set up organized stock full of chests with item frames that had mob spawn eggs in them. It looks weird and messy with these kinds of behaviors :/

**Comment by SepSol** [comment]
For **Player Statue**, it would be great if it supported this command for giving named items though:
`/give @p statues:player_statue{display:{name:"{\"text\":\"SepSol\"}"}}`

**Comment by SepSol** [comment]
If this is intended behavior because it is meant to be used with invisible item frames, maybe as this is a mod, you could add your own invisible item frame which displays statues just like how they are in vanilla item frames and then adjust the look of statues on vanilla item frames to be more normal. Just saying...

**Comment by ShyNieke** [comment]
Actually this is idea i can get behind, will look in to it but i can't promise when and if it will be added

**Comment by SepSol** [comment]
Thanks a lot!

**Comment by SepSol** [comment]
@ShyNieke  Since [Quark](https://www.curseforge.com/minecraft/mc-mods/quark/files/2822806) mod is now officially released for 1.14.4, you might want to use their [transparent item frame](https://quark.vazkii.net/#features) feature for this. I know they had differentiated the look of banners on normal vs glass (transparent) item frames, so it should be possible for you to do this too. Thought I should give you a heads up on that :)
