### ISSUE TITLE
Another Player Statue that can get its skin from a URL

### ISSUE THREAD

**Issue by sepsol** [ShyNieke/StatuesMod#31]
## SUGGESTIONS
- [x] I would like to propose new content.
- [ ] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTION INFORMATION

It could be useful to have custom skinned player statues laying around. You could make a temple with it! I would like to suggest some new things other than this as well:

- being able to place armor and tools or shield on player statues
- being able to rotate statues every 45 degrees - just like how item frames work

**Comment by SepSol** [comment]
It could be useful to have custom skinned player statues laying around. You could make a temple with it! I would like to suggest some new things other than this as well:

- being able to place armor and tools or shield on player statues
- being able to rotate statues every 45 degrees - just like how item frames work

**Comment by Mrbysco** [comment]
Version 0.1.6.5 implements a big Player Statue (as tall as a normal player) that is fully pose-able and can wear armor and can hold items. And can also be rotated any amount of degrees.
