### ISSUE TITLE
Different poses for statues

### ISSUE THREAD

**Issue by sepsol** [ShyNieke/StatuesMod#32]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.

**Comment by SepSol** [comment]
Statues don't look good when they are placed on the side of a wall or on a crafting table. also it would be nice to be able to rotate them around every 45 degrees, just like how item frames work.

**ON THE SIDE OF A WALL**
For some statues like spiders, it could be like how they currently look like when placed in an item frame.

**ON CRAFTING TABLES**
They are upside down. Their face is towards the ground which is weird. (I'm using [CraftingStation](https://www.curseforge.com/minecraft/mc-mods/crafting-station) mod)

![image](https://user-images.githubusercontent.com/47871887/68039618-c2f22100-fce1-11e9-9809-0492f645b317.png)
