### ISSUE TITLE
Allow Waterlogging of the Display Stand

### ISSUE THREAD

**Issue by WenXin20** [ShyNieke/StatuesMod#36]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

## SUGGESTION INFORMATION
It would be great to be able to waterlog the Display Stand. That way, if any statues are placed underwater, the display stand can also be used.

**Comment by ShyNieke** [comment]
this will definitly be added as it is a oversight on our part, they should have been water loggable, Sorry!

**Comment by WenXin20** [comment]
It's no problem!
