### ISSUE TITLE
Statues of Mob Skeletons

### ISSUE THREAD

**Issue by GentlemanGnu** [ShyNieke/StatuesMod#37]
## SUGGESTIONS
- [x] I would like to propose new content.
- [ ] I would like to propose changes.
- [ ] I would like to propose another thing.

## SUGGESTION INFORMATION
As per our discussion earlier today, Shy, I would like to suggest that you add Skeletons statues of the mobs to your statues mod.  In the attached image is the island at the end of my demonstration of the Fossils and Archaeology Mod's implementation of this feature (for its dinosaurs)  Including the resizing by adding bones.  Maybe for the shrinking option you thought of shift right clicking on the statue to "remove" a bone could work?

I think this would be a really cute addition to the mod.
![2020-04-11_00 19 40](https://user-images.githubusercontent.com/47682720/79002943-e2488080-7b94-11ea-89b9-550a7c238495.png)

**Comment by Mrbysco** [comment]
I don't think it'll be possible for me to make statues grow bigger when right clicked as I don't think there's a way to make a block appear large. Especially the hitbox.

The skeleton mobs can be an addon to Statues but for that you'll have to talk to @ShyNieke

**Comment by ShyNieke** [comment]
Unfortunately I don't think this is something we will do anytime soon, I will close this suggestion now, sorry that we won't do it :c
