### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by JGitto** [ShyNieke/StatuesMod#38]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 12.23.5.2838
* Mod Version: statues-1.12.X-0.8.9.1
* Java Version: Java 8

## Issue Description
When dying on my multiplayer server almost always my client crashes. This happens in the SkyFactory 4 modpack. Crash report says it is an IllegalArgumentException in the BlockStateContainer function after being called by the PlayerStatueRenderer.render() function.

## Reproduce Steps
Dying to any cause whilst having any playerstatue in the world

## Additional Information
Crash reports:
https://pastebin.com/yx7FMqjJ
https://pastebin.com/ZZjK5ers

**Comment by Mrbysco** [comment]
Could you try this version?
https://github.com/ShyNieke/StatuesMod/releases/tag/0.8.9.2

**Comment by JGitto** [comment]
Thanks. This fixed the crash. I still need everyone playing on my server to update the mod manually, right? Or can you contact people to update the mod in the modpack?

**Comment by Mrbysco** [comment]
Is it completely fixed? As in any new death it also doesn't crash?
If it's for sure fixed 100% I can upload it to curse.

Until SkyFactory releases an update you'll have to get people to update it themselves.

**Comment by JGitto** [comment]
I died to several causes and didn’t crash
