### ISSUE TITLE
1.15.2 crafting table bugged for some recipes

### ISSUE THREAD

**Issue by ArMoReDfUrY** [ShyNieke/StatuesMod#40]
## Client Info
* Minecraft Version: 1.15.2

* Forge Version: 31.2.21
* Mod Version: 1.15.2-0.1.3.2
* Java Version: 1.8.0_51

After installing Statues, crafting table is broken for a bunch of recipes from various mods e.g. sandbag mod, Silent Gears crafting bench recipe result is broken and closing the crafting table dupes 1 of the items in the recipe, which item is random.

this issue causes no crash.

removing statues resolved the issue for me.

add silent gear + silent lib + sandbag + Statues.
try to craft sandbag.
try to craft silent gear crafting bench.

## Additional Information
mod list. made after removing statues, so it's not in the list:   https://pastebin.com/TmRY0VBQ

**Comment by Mrbysco** [comment]
Could you provide a log with Statues installed?

**Comment by ArMoReDfUrY** [comment]
sorry for the delay, i am investigating this issue at the moment. i think it may be caused by the Polymorph mods recipe collision checks bugging out. not sure yet as this is a tricky bug to identify. i am working with the polymorph dev to resolve the issue.
i will run some more tests on statues once poly is sorted out, i'm betting it will resolve itself.

**Comment by ArMoReDfUrY** [comment]
i have resolved the issue and it is a direct result of the Polymorph mod not liking updates on existing worlds.

https://github.com/TheIllusiveC4/Polymorph/issues/10#issuecomment-651686691

i am closing this now.
