### ISSUE TITLE
Possible way of making adding modded mob statues easier

### ISSUE THREAD

**Issue by Corvus20** [ShyNieke/StatuesMod#43]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [ ✔] I would like to propose changes.
- [ ✔] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTION INFORMATION

I saw that, at least from what I can tell, you are adding modded mob statues manually as time goes for mods requested. You could probably make this easier on yourself by having code to fetch the entity model, like how JustEnoughResources shows the mob in question when on the mob drops tab, modded or not. A similar method could be applied to statues, and the statue core colors could be made from fetching colors of the entity, or more likely, its spawn egg's colors. I am by no means experienced in modding in the slightest, but I do know some base concepts, just not the coding bit, somehow. I don't know if this has been mentioned before, but I figured I might as well mention it just in case.

I have been looking for a mob statue/trophy mod like this for a while now, and if the modded mob support thing comes in full, I will be sold on this mod. This mod is probably the closest thing to some of the old trophy mods back in 1.7.10, and I hope it succeeds. I can't wait to see what lies ahead!

**Comment by ShyNieke** [comment]
Sorry atm it is not possible to add modded statues as each statue is hand made and hand textured.
If you want to try and make modded statues I want to invite you to my discord where I made a new channel for modded statues for if people want to make some modded statues models and textures that way we will be able to support modded statues sooner than later. (and of course with each modded statue made credit will be given to the right people)

https://discord.gg/0lO0JGD7rg2yJTNJ
