### ISSUE TITLE
Waterlogging Breaks Water Source

### ISSUE THREAD

**Issue by WenXin20** [ShyNieke/StatuesMod#44]
## Client Info
* Minecraft v1.16.5
* Forge v36.0.13
* Mod v0.1.6.5
* Java v1.8.0

## Issue Description
- All waterloggable statues & the display stand deletes the water source when first placed.

## Reproduce Steps
1. Place statue underwater
2. Observe
3. Compare to a vanilla waterloggable block.

**Comment by Mrbysco** [comment]
Located the issue and its fixed next release.

**Comment by WenXin20** [comment]
Thanks!
