### ISSUE TITLE
Placing a statue with invalid nickname creates a insane lag spike until the statue is broken

### ISSUE THREAD

**Issue by MrRubberDucky** [ShyNieke/StatuesMod#54]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.1.23
* Mod Version: 0.1.7.1 & 0.1.7.2
* Java Version: 8

## Issue Description
Creating a Small Statue with a invalid nickname (nonexistent minecraft account) results in a intense lag spike until the statue is broken. This also touches player statues spawned with Player Statue Spawn Egg (and renamed with a name tag)
The lag spike is worse with the "big" statue spawned from Player Statue Spawn Egg

## Reproduce Steps
1. Give yourself a small statue or spawn the "big" version as I like to call it
2. Rename the small statue in the anvil to some random name ex. liamtc1234 / rename the name tag for the big version
3. Place the small statue on the floor. Watch as the game cripples in performance / apply the name tag onto the big version

## Additional Information
Crash: https://pastebin.com/ycXs25EV (These happened with 0.1.7.1 but i'll still include them)
Crash 2: https://pastebin.com/xH0igwTy:
edit: These crashes were triggered by placing the statue, breaking it and then trying to hover over it in my inventory (or attempting to interact with them in any way), after restarting the game the issue is gone. No idea how to reproduce this one though.

**Comment by Mrbysco** [comment]
I'm only able to reproduce the crash which is a mistake of my part, I can't reproduce the lag spike

**Comment by MrRubberDucky** [comment]
> 
> 
> I'm only able to reproduce the crash which is a mistake of my part, I can't reproduce the lag spike

That was pretty quick, nice job!
Though, found the issue, it seems to steem from [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe) mod, removing it and hovering over the statues no longer creates dreadful lag. Not sure why that happens though, might be worth looking into it though probably it's not worth anyones time.

**Comment by Mrbysco** [comment]
I know from experience that TOP had some weirdness with entity rendering to the point where it span really fast.. dunno if it's still the case. But glad you found the lag source.

**Comment by Mrbysco** [comment]
I'll look into it and create an issue where needed if I find what the exact cause is 👍
