### ISSUE TITLE
Player statues don't display Alex-type skins correctly

### ISSUE THREAD

**Issue by deactivate-BL** [ShyNieke/StatuesMod#55]
## General Info
- [ ] I am running a modpack
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the mod

## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.2.0
* Mod Version: Statues-1.16.5-0.1.7.3
* Java Version: 1.8.0_292

## Issue Description
Player statues only spawn Steve-type versions, not Alex-type versions. Or, Player statues don't allow Alex-type skins to properly wrap around the spawned model. When a player is using an Alex-type skin, the Player statue has black bars at the back of its arms.

## Reproduce Steps
Spawn Player statue while an Alex-type skin is applied to the player.

## Additional Information
https://imgur.com/a/TckRzu8

**Comment by Mrbysco** [comment]
New version has been released which includes a fix courtesy of @sekwah41 :)
