### ISSUE TITLE
[Bug]: Unable to register name on small statue character

### ISSUE THREAD

**Issue by lSherozl** [ShyNieke/StatuesMod#64]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.28

### Mod version

1.7.6 Latest 1.16.5 Version

### Java version

Java 8 321

### Issue Description

Does not show my name on the smaller player statues stature, it does show it on the bigger one, here is an image:
![277517970_300850588790221_2199820208817243622_n](https://user-images.githubusercontent.com/65663746/162611023-bb132475-1b3c-47e7-b17a-76671956f4e9.jpg)

**Comment by lSherozl** [comment]
> What is your in-game name so I can see if I can reproduce it?

Sorry just saw this my in game name is.......  ISherozI ......that is with 2 capital I's not lowercase L's

**Comment by lSherozl** [comment]
I am also playing on a modpack, better Minecraft plus, do not know if its a conflict with some mod, but the bigger statue of me works fine

**Comment by Mrbysco** [comment]
I think this is an issue in 1.16 Jade. In the 1.18 version of Jade it renders the name correctly

**Comment by lSherozl** [comment]
> I think this is an issue in 1.16 Jade. In the 1.18 version of Jade it renders the name correctly

jade is not a mod im using though

**Comment by lSherozl** [comment]
> I think this is an issue in 1.16 Jade. In the 1.18 version of Jade it renders the name correctly

So I should talk to the Jade owners?

**Comment by Snownee** [comment]
so what the error is? it should be logged in WailaErrorOutput.txt

**Comment by Snownee** [comment]
it's under .minecraft folder

**Comment by Mrbysco** [comment]
[WailaErrorOutput.txt](https://github.com/ShyNieke/StatuesMod/files/8465606/WailaErrorOutput.txt)
I happen to have the output from when I was trying to debug the issue

**Comment by Mrbysco** [comment]
The code that gives the Player Statue's block it's name hasn't really changed between the 1.16 and 1.18 version

**Comment by Snownee** [comment]
I think this is the cause: https://github.com/ShyNieke/StatuesMod/blob/1.16.5/src/main/java/com/shynieke/statues/tiles/PlayerTile.java#L218-L221

I think the return value should be nonnull if you return `true` in `hasCustomName`

**Comment by Mrbysco** [comment]
I wonder why that works in 1.18 🤔 Did Jade's internal change

**Comment by Snownee** [comment]
yes, I added a null check.

**Comment by Mrbysco** [comment]
A new version has been uploaded to CurseForge to fix the issue 👍

**Comment by lSherozl** [comment]
> A new version has been uploaded to CurseForge to fix the issue 👍



> yes, I added a null check.

Thank you both
