### ISSUE TITLE
[Suggestion]: Full sized player statue instead of baby versions 

### ISSUE THREAD

**Issue by pantsguyapp** [ShyNieke/StatuesMod#66]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Beside the tiny player statues versions, I propose that we should have bigger statues that are the same size as normal players.

**Comment by ShyNieke** [comment]
This is already a feature, use a statue core on a player statue, statue cores can be obtained by killing statue bats

**Comment by pantsguyapp** [comment]
Ok but why does the big version a mob instead of a block like the baby statues? If I amass them in my base there will be significantly more lag.

**Comment by Mrbysco** [comment]
The player statue blocks render the same as a mob would so the amount of lag is equal

**Comment by pantsguyapp** [comment]
Still, why are they mobs?

**Comment by Mrbysco** [comment]
Because json models don't support hot-swapping textures last I checked. Having a bunch of Player statues is no different than having a bunch of player skulls (Skulls also are rendered mob-like)
