### ISSUE TITLE
[Suggestion]: Big player statues should have a slab option.

### ISSUE THREAD

**Issue by pantsguyapp** [ShyNieke/StatuesMod#67]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Should have an place where different slabs can be put in and thus make the statues stand on said slab

**Comment by pantsguyapp** [comment]
And if there is a slab inside the slot there should be another slot for one item/block. Idea taken from Vault Hunter's omega statues.

**Comment by Mrbysco** [comment]
No plans to add anything like this
