### ISSUE TITLE
Suggestion - display pedestal equivalent

### ISSUE THREAD

**Issue by generrosity** [ShyNieke/StatuesMod#7]
Hello! Love your mod. Cutest thing even.

Could I suggest a variant of the player statue that could accept a item being right-clicked onto and off the model? I understand there might be too many pedestals out there already, but somehow we can't find non-frame ones in Foolcraft2.

Display wise, perhaps as either as the hands out and the object tile "being held", or as a slowly rotating object over outstretched arms.

Could I also suggest an object that could convert a bat to a statue bat?

**Comment by ShyNieke** [comment]
Posable player statues have been added to statues, this allows many things including allowing them to hold items and armor
