### ISSUE TITLE
[Bug]: Loot is missing after some first interactions with Peaceful Statues

### ISSUE THREAD

**Issue by zaciam** [ShyNieke/StatuesMod#70]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

14.23.5

### Mod version

0.8.10

### Java version

Java 8 Update 341

### Issue Description

After some interactions the statues loos their loot table even in JEI and stop dropping at all:
![screenshot](https://user-images.githubusercontent.com/5081153/192109069-95f1d60d-1d29-4509-8696-6c89625264d5.png)
Tested also the version before statues-1.12.X-0.8.9.2.jar, had the same issue.

It seems to be related with what they dropping as they first loos their loot partly (Iron ingot disappears later then the rotten flesh).

I created a test world. The behavior here is even more strange as the loot table loot increases now with each interaction:
![image](https://user-images.githubusercontent.com/5081153/192109834-c2346791-1913-4293-a3e5-c8803124869e.png)

**Comment by Mrbysco** [comment]
Like specified in the changelog for 0.8.10 **Unless other major issues are found, no further support for 1.12 will be given**

**Comment by zaciam** [comment]
This is a major issue.

@Mrbysco: why you comment that?

**Comment by Mrbysco** [comment]
> @Mrbysco: why you comment that?

Because the feature you're talking about doesn't exist in the latest supported version which is the version on 1.19.2.
And like many devs, we have moved on and way past 1.12 and don't offer support unless it's game breaking.

**Comment by Mrbysco** [comment]
While browsing through the old 1.12 code I found some issues I've wanted to fix and by doing so I've probably fixed this issue.
A new jar has been uploaded which will hopefully be the last 1.12 build of Statues

**Comment by zaciam** [comment]
Great! I will test it.

**Comment by zaciam** [comment]
Thank you. The ``stack.copy()`` has fixed it. :)
