### ISSUE TITLE
[Bug]: Unable to craft upgrades

### ISSUE THREAD

**Issue by InsaneVirus** [ShyNieke/StatuesMod#72]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.52

### Minecraft version

1.19.2

### Mod version

1.19.2-0.3.0-rc.2

### Java version

8

### Issue Description

Unable to Craft Statue upgrades, Chisel option does not show up.

Tested on level 3 statue and level 1 statue to ensure it was not an issue with identifying levels

Initially tested with Spawning and Mob Killer Upgrades

_Note: Unreleased modpack currently in Beta Testing (speak to shy for more info)_

### Additional Information

![2022-11-16_19 17 21](https://user-images.githubusercontent.com/3320707/202274631-2d0f6bd1-97e5-48f2-a0d9-67f362a76e70.png)

![2022-11-16_19 17 23](https://user-images.githubusercontent.com/3320707/202274642-48e6b3ff-27b4-4bce-9123-c669f61c7440.png)

**Comment by Mrbysco** [comment]
Fixed in the next alpha
