### ISSUE TITLE
[Bug]: JEI Integration only displays Spawner II not Spawner I

### ISSUE THREAD

**Issue by InsaneVirus** [ShyNieke/StatuesMod#73]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.52

### Minecraft version

1.19.2

### Mod version

1.19.2-0.3.0-rc.2

### Java version

8

### Issue Description

When searching for upgrade recipes I can only see Spawner II not Spawner I

_Note: Unreleased modpack currently in Beta Testing (speak to shy for more info)_

### Additional Information

![2022-11-16_19 34 01](https://user-images.githubusercontent.com/3320707/202276586-a3e35631-3759-421c-a181-f20d69088c43.png)

**Comment by Mrbysco** [comment]
Fixed in the next alpha
