### ISSUE TITLE
[Bug]: Statues do not "drop" Loot

### ISSUE THREAD

**Issue by InsaneVirus** [ShyNieke/StatuesMod#74]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.52

### Minecraft version

1.19.2

### Mod version

1.19.2-0.3.0-rc.2

### Java version

8

### Issue Description

Placing a statue down does not produce any loot

I have a level 3 Blaze statue which does not drop any loot.

Placed down with a ranged collector and 0 blaze rods or blaze dust in 30 mins. 

Either it does not work or it is far too slow. 

Note: Unreleased modpack currently in Beta Testing (speak to shy for more info)

**Comment by Mrbysco** [comment]
Loot is only dropped when upgraded with Looting

**Comment by InsaneVirus** [comment]
Guess that makes sense, in which case can you add it to shy's documentation suggestions 😉

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
