### ISSUE TITLE
[Bug]: Mob Killer Upgrade causes crash

### ISSUE THREAD

**Issue by InsaneVirus** [ShyNieke/StatuesMod#75]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.57

### Minecraft version

1.19.2

### Mod version

0.3.0-rc7

### Java version

8

### Issue Description

Describe the bug
Statues Mob Killer Upgrade causes server crash when damaging mobs

Steps to reproduce
Upgrade Statue with Mob Killer I and Spawner I and spawn a mob
Let Statue cause damage to Mob
Crash

Expected behavior
Not to Crash

Additional context
If anyone goes near my base it will crash server due to statue spawning and then damaging the mob.

### Additional Information

Log Files
(https://gist.github.com/InsaneVirus/aab9684f521ab4a80578e52256f0adee)

**Comment by Mrbysco** [comment]
I see no mention of statues in the log, I only see stuff related to a mod called `It Shall Not Tick (ISNT)`

**Comment by Mrbysco** [comment]
I'll look into it
